name: Linux

on: [push]

jobs:
  linux-test:
    runs-on: ubuntu-20.04
    continue-on-error: true
    strategy:
      matrix:
        branch: [default]
        python-version: [3.8, 3.9, '3.10', '3.11']
    container: monetdb/dev-builds:${{ matrix.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

            # - name: Setup database
            #   run: |
            #     cd test 
            #     ./initfarm.sh
            #     ./initdb.sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Run Tox
        run: tox
