name: Linux

on:
  push:

  schedule:
    - cron:  '15 2 * * *'

jobs:
  linux-test:
    runs-on: ubuntu-24.04
    env:
      DATABASE: test
    continue-on-error: true
    services:
      monetdb:
        image: "monetdb/dev-builds:Dec2025"
        env:
          MDB_CREATE_DBS: '${{ env.DATABASE }}'
          MDB_DB_ADMIN_PASS: monetdb
        ports:
          - 50000:50000
    strategy:
      matrix:
        branch: [default]
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pymonetdb
        run: pip install pymonetdb

      - name: Prepare database
        shell: python
        run: |
          import logging, os, pymonetdb
          logging.basicConfig(level=logging.DEBUG)
          dbname = os.environ['DATABASE']
          conn = pymonetdb.connect(database=dbname)
          cursor = conn.cursor()
          cursor.execute("CREATE SCHEMA test_schema")
          cursor.execute("CREATE SCHEMA test_schema2")
          cursor.execute("ALTER USER monetdb SET SCHEMA test_schema2")
          conn.commit()

      - name: Run tests
        run: make pytest
